Add new

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -17,9 +17,12 @@ jobs:
           username: ${{ secrets.DOCKER_HUB_USERNAME }}
           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 
-      - name: Pull Docker image from docker
-        run: sudo docker pull sarker24/universal-books-server:latest
-      - name: Delete Old docker container
+      - name: Pull Docker image from Docker Hub
+        run: |
+          docker pull sarker24/universal-books-server:latest || (echo "Failed to pull Docker image." && exit 1)
+
+      - name: Delete Old Docker container
         run: sudo docker rm -f universal-books-server || true
+
       - name: Run Docker Container
         run: sudo docker run -d -p 3000:3000 --name universal-books-server sarker24/universal-books-server
